---
- name: Install packages
  apt:
    name: "{{ _samba_packages }}"

- name: Create users # @see https://github.com/bertvv/ansible-role-samba/blob/master/tasks/main.yml
  shell: >-
    (echo {{ item.password }}; echo {{ item.password }}) \
    | smbpasswd -s -a {{ item.username }}
  register: _output
  changed_when: "'Added user' in _output.stdout"
  with_items: "{{ samba_users }}"

- name: Update config file
  blockinfile:
    path: /etc/samba/smb.conf
    insertafter: EOF
    block: |
      [{{ item.name }}]
         path = {{ item.path }}
         read only = no
         guest ok = no
  with_items: "{{ samba_shares }}"
  notify: restart-samba

- name: Start service
  service:
    name: "{{ _samba_service }}"
    state: started
    enabled: yes